spring.application.name=fileshare-api

aws.bucket.name=fileshare-suyash-storage-828659494565-ap-south-1-an
aws.access-key=AKIA4B37UN2SY6Y4PIBG
aws.secret-key=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
aws.region=ap-south-1

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.data.mongodb.uri=mongodb+srv://2k23cs2314112_db_user:FileShare123@cluster0.przhtbo.mongodb.net/fileshare?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=fileshare