spring.application.name=fileshare-api

aws.bucket.name=fileshare-suyash-storage-828659494565-ap-south-1-an
aws.access-key=AKIA4B37UN2SY6Y4PIBG
aws.secret-key=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
aws.region=ap-south-1