- name: Restart Application
  uses: appleboy/ssh-action@v1.2.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      set -e

      cd /home/ubuntu/share-service

      pkill -f '.jar' || true

      sleep 2

      JAR=$(find . -name "*.jar" | head -n 1)

      echo "Starting $JAR"

      nohup java -jar "$JAR" > app.log 2>&1 < /dev/null &

      disown

      sleep 5

      ps -ef | grep java | grep -v grep